name: Forge Toolkit
author: Carver
description: Custom automation tools for the Forge ecosystem.
version: "1.0.0"

tools:
  - name: ForgeBuilder
    class_name: ForgeBuilder
    file_name: forge_tools
    description: Builds Forge project components.
  - name: ForgeAnalyzer
    class_name: ForgeAnalyzer
    file_name: forge_tools
    description: Analyzes Forge data and outputs summaries.
